### ISSUE TITLE
Driver is not supporting ssl

### ISSUE THREAD

**Issue by vaishnavimutha** [housepower/ClickHouse-Native-JDBC#360] opened 2021-08-11 12:39 UTC
### Environment

- OS version: 
- JDK version:
- ClickHouse Server version: 
- ClickHouse Native JDBC version:
- (Optional) Spark version: N/A
- (Optional) Other components' version: N/A

### Error logs

```
paste your error logs here
```

**Comment by f1yegor** [comment] 2021-08-18 13:09
duplicate of !203

**Closed** 2023-09-22 22:08 UTC
