### ISSUE TITLE
clickhouse-jdbc is faster than ClickHouse-Native-JDBC

### ISSUE THREAD

**Issue by thangntt** [housepower/ClickHouse-Native-JDBC#134] opened 2020-07-30 07:31 UTC
Hi all,

I tested the benchmark between clickhouse-jdbc and ClickHouse-Native-JDBC, ClickHouse-Native-JDBC don't really faster as https://github.com/housepower/ClickHouse-Native-JDBC/blob/master/Benchmark.md 

Thanks.

**Comment by sundy-li** [comment] 2020-07-30 10:52
Could you show the results of your tests?

**Comment by thangntt** [comment] 2020-07-31 09:43
> Could you show the results of your tests?
Hi @sundy-li, 
1.  make 500 queries on 4000.0000 records and results test:
     clickhouse-jdbc make 15 seconds
     ClickHouse-Native-JDBC make 234 seconds  
2. my code
```
//class make connection
public class ClickHouseJDBCUtil {

    public static ClickHouseConnectionImpl getConnectionJDBCHTTP() throws SQLException {
        ClickHouseDataSource dataSource = new ClickHouseDataSource("jdbc:clickhouse://10.252.9.17:8123/db_test?keepAliveTimeout=300000&socket_timeout=300000&dataTransferTimeout=300000");
        ClickHouseConnectionImpl connection = (ClickHouseConnectionImpl) dataSource.getConnection();
        return connection;
    }

    public static Connection getConnectionJDBCNative() throws SQLException {
        Enumeration<Driver> drivers = DriverManager.getDrivers();
        while (drivers.hasMoreElements()) {
            DriverManager.deregisterDriver(drivers.nextElement());
        }
        DriverManager.registerDriver(new ClickHouseDriver());
        Connection connection = DriverManager.getConnection("jdbc:clickhouse://10.252.9.17:9000");
        return connection;
    }
}

//class test benchmark
public class TestFetchData {
    public static void main(String[] args) {
        long start = System.currentTimeMillis();
        try {
            List<ThreadTestFetchData> threads = new ArrayList<ThreadTestFetchData>();
            for (int i = 0; i < 10; i++) {
                ThreadTestFetchData t = new ThreadTestFetchData();
                threads.add(t);
                t.start();
            }
            for (ThreadTestFetchData t: threads) {
                t.join();
            }
        } catch (Exception e) {

        }
        long end = System.currentTimeMillis() - start;
        System.out.println("===============> " + end);
    }
}

class ThreadTestFetchData extends Thread {

    public void run() {
        try {
            Connection connection = ClickHouseJDBCUtil.getConnectionJDBCNative();
//            Connection connection = ClickHouseJDBCUtil.getConnectionJDBCHTTP();
            for (int i = 0; i < 10; i++) {
                CertificateData data = CertificateData.random();
                test1(data, connection);
                test2(data, connection);
                test3(data, connection);
                test4(data, connection);
                test5(data, connection);
            }

            System.out.println("done");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void test1(CertificateData data, Connection c) throws SQLException {
        PreparedStatement p = c.prepareStatement("select * from db_test.certificate WHERE name_certificate_profile = ? AND  effective_date_cert > ? AND effective_date_cert < ? limit 100");
        p.setString(1, data.name_certificate_profile);
        p.setTimestamp(2, new Timestamp(data.effective_date_cert.getTime()));
        p.setTimestamp(3, new Timestamp(data.expire_date_cert.getTime()));
        ResultSet rs = p.executeQuery();
    }

    public void test2(CertificateData data, Connection c) throws SQLException {
        PreparedStatement p = c.prepareStatement("select * from db_test.certificate WHERE timevalidity_cert = ? AND  effective_date_cert > ? AND effective_date_cert < ? limit 100");
        p.setInt(1, data.timevalidity_cert);
        p.setTimestamp(2, new Timestamp(data.effective_date_cert.getTime()));
        p.setTimestamp(3, new Timestamp(data.expire_date_cert.getTime()));
        ResultSet rs = p.executeQuery();
    }

    public void test3(CertificateData data, Connection c) throws SQLException {
        PreparedStatement p = c.prepareStatement("select * from db_test.certificate WHERE id_certificate_profile = ? AND  effective_date_cert > ? AND effective_date_cert < ? limit 100");
        p.setInt(1, data.id_certificate_profile);
        p.setTimestamp(2, new Timestamp(data.effective_date_cert.getTime()));
        p.setTimestamp(3, new Timestamp(data.expire_date_cert.getTime()));
        ResultSet rs = p.executeQuery();
    }

    public void test4(CertificateData data, Connection c) throws SQLException {
        PreparedStatement p = c.prepareStatement("select * from db_test.certificate WHERE postal_code = ? AND  effective_date_cert > ? AND effective_date_cert < ? limit 100");
        p.setString(1, data.postal_code);
        p.setTimestamp(2, new Timestamp(data.effective_date_cert.getTime()));
        p.setTimestamp(3, new Timestamp(data.expire_date_cert.getTime()));
        ResultSet rs = p.executeQuery();
    }

    public void test5(CertificateData data, Connection c) throws SQLException {
        PreparedStatement p = c.prepareStatement("select * from db_test.certificate WHERE type_token = ? AND  effective_date_cert > ? AND effective_date_cert < ? limit 100");
        p.setString(1, data.type_token);
        p.setTimestamp(2, new Timestamp(data.effective_date_cert.getTime()));
        p.setTimestamp(3, new Timestamp(data.expire_date_cert.getTime()));
        ResultSet rs = p.executeQuery();
    }

}
```
3. table
```
ATTACH TABLE certificate
(
    `serial_cert` String,
    `status_cert` Int8,
    `change_status_date_cert` DateTime,
    `change_status_reason_cert` String,
    `expire_date_cert` DateTime,
    `effective_date_cert` DateTime,
    `subject_dn_cert` String,
    `subject_email_cert` String,
    `timevalidity_cert` Int8,
    `email_customer` String,
    `name_customer` String,
    `username_customer` String,
    `phone_customer` String,
    `address_customer` String,
    `name_certificate_profile` String,
    `id_certificate_profile` Int8,
    `serial_token` String,
    `type_token` String,
    `id_request_user` Int8,
    `name_request_user` String,
    `serial_request_user` String,
    `id_approve_user` Int8,
    `name_approve_user` String,
    `serial_approve_user` String,
    `name_department` String,
    `id_department` Int8,
    `postal_code` String
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(effective_date_cert)
ORDER BY (effective_date_cert, serial_cert)
SETTINGS index_granularity = 8192
```

**Comment by sundy-li** [comment] 2020-08-01 03:14
@thangntt  Thanks for the feedback.
But I can't reproduce it, because I don't have your datasets.
Yet I create a simple test from your code, but it shows the results that `native-jdbc` performs better than `http-jdbc`. https://www.onlinegdb.com/BJ32hLM-D

Some advice on benchmark:
- I think in the case of jdbc benchmark, concurrent benchmark is the same as the single benchmark.
- Results may be different in varying datasets.
- OLAP query results are always with fewer columns and rows.

**Comment by thangntt** [comment] 2020-08-01 09:27
Hi @sundy-li 
Thank you for the reply, 

I tested the benchmark your code and the results that http-jdbc performs better than navite-jdbc.
I tested open a new connection and the results that http-jdbc performs better than navite-jdbc.

I think native-jdbc must be faster, I don't understand why that is.

file config click-house: 
https://onlinegdb.com/H1qBHnG-w

**Comment by sundy-li** [comment] 2020-08-01 11:14
Ok, which ClickHouse version are you using?  I am using `19.18.1` and `20.3.8.53`

**Comment by thangntt** [comment] 2020-08-02 03:20
I am using 20.2.1.2183 and 20.4.7.67
I try on the above version, but result is the same

**Comment by thangntt** [comment] 2020-08-02 03:32
I find test per by other people
https://groups.google.com/forum/#!msg/clickhouse/dsUTnHihjs4/NOi0y0jxAAAJ

**Comment by sundy-li** [comment] 2020-08-02 07:49
> I found the performance test results of others
> https://groups.google.com/forum/#!msg/clickhouse/dsUTnHihjs4/NOi0y0jxAAAJ

That's the old version results. Which Native-JDBC and clickhouse-jdbc version are you using ?

**Comment by thangntt** [comment] 2020-08-02 07:53
> > I found the performance test results of others
> > https://groups.google.com/forum/#!msg/clickhouse/dsUTnHihjs4/NOi0y0jxAAAJ
> 
> That's the old version results. Which Native-JDBC and clickhouse-jdbc version are you using ?

        <dependency>
            <groupId>ru.yandex.clickhouse</groupId>
            <artifactId>clickhouse-jdbc</artifactId>
            <version>0.2.4</version>
        </dependency>
        <dependency>
            <groupId>com.github.housepower</groupId>
            <artifactId>clickhouse-native-jdbc</artifactId>
            <version>2.1-stable</version>
        </dependency>

**Comment by sundy-li** [comment] 2020-08-02 09:54
@thangntt  I think your configs and machine may lead to the diffs. I create a simple PR  #135 , and you can find the ci bench results. 
BTW, I think the select query performance is not as important as the insert query. So most benchmark we just bench the batch insert performance.

**Comment by sundy-li** [comment] 2020-08-19 01:34
Closing this issue, feel free to re-open a closed issue if needed

**Closed by sundy-li** 2020-08-19 01:34 UTC
