### ISSUE TITLE
When Using Spark JDBC， the inserted data field contains Chinese，if I haven't used limit，it will appear ‘?’

### ISSUE THREAD

**Issue by NighterCoder** [housepower/ClickHouse-Native-JDBC#128] opened 2020-06-24 06:10 UTC
### JDBC version in pom.xml
<dependency>
      <groupId>com.github.housepower</groupId>
      <artifactId>clickhouse-native-jdbc</artifactId>
      <version>2.1-stable</version>
 </dependency>

### ClickHouse version
19.3.5

### Other descriptions
`val df = spark.sql(
     s"""
        |SELECT member_id,
        |  cell_phone ,
        |  card,
        |  age,
        |  age_range,
        |  sex,
        |  birthday,
        |  case when oversea_life_cycle is null then '-1' else oversea_life_cycle end as oversea_life_cycle,
        |  case when birth_season is null then '-1' else birth_season end as birth_season
        |FROM persona.flat_table
        |WHERE age_range is not null
      """.stripMargin)`
When I haven't used limit , finally the chinese column will partly appear '?'，for example 
![image](https://user-images.githubusercontent.com/26673766/85507045-3a374500-b624-11ea-8ce9-c01e52be71e3.png)
But I have used limit in the spark sql，
`  val df = spark.sql(
     s"""
        |SELECT member_id,
        |  cell_phone ,
        |  card,
        |  age,
        |  age_range,
        |  sex,
        |  birthday,
        |  case when oversea_life_cycle is null then '-1' else oversea_life_cycle end as oversea_life_cycle,
        |  case when birth_season is null then '-1' else birth_season end as birth_season
        |FROM persona.flat_table
        |WHERE age_range is not null
        |limit ${args(6)}
      """.stripMargin)`
the cloumn which have Chinese values will present normally

**Comment by sundy-li** [comment] 2020-06-24 08:02
Hi, I can't figure out the problem, could you create a simple java uint test to reproduce it?

**Comment by sundy-li** [comment] 2020-08-02 13:13
Can't reproduced in [test-cases](https://github.com/housepower/ClickHouse-Native-JDBC/blob/master/src/test/java/com/github/housepower/jdbc/BatchInsertITest.java#L31).

Closing this issue, feel free to re-open a closed issue if needed

**Closed by sundy-li** 2020-08-02 13:13 UTC
